package com.sunforge.properties;

public enum LocalizationField {
    //Command messages

    //Used in /start
    START_CHOOSE_SUBGROUP,
    START_WISH,

    //GENERAL
    FIRST_SUBGROUP,
    SECOND_SUBGROUP,
    BACK,

    //DAYS
    //SHORTENED
    MONDAY_SHORTENED,
    TUESDAY_SHORTENED,
    WEDNESDAY_SHORTENED,
    THURSDAY_SHORTENED,
    FRIDAY_SHORTENED,
    SATURDAY_SHORTENED,
    SUNDAY_SHORTENED,

    //SETTINGS
    SETTINGS,

    //SCHEDULE_MENU
    TODAY,
    TOMORROW,
    WEEK,
    NEXT_WEEK,

    //SCHEDULE
    SCHEDULE,
    SCHEDULE_RESPONSE,
    TIME_SCHEDULE,
    DAYOFF,
    SUBJECT,
    CLASS,
    TEACHER,

    //ERRORS
    ERROR_DB_RETRIEVE_SUBGROUP,
    ERROR_DB_RETRIEVE_SCHEDULE,
    ERROR_INPUT_INVALID_COMMAND,
    ERROR_INPUT_INVALID_CALLBACK
}
